// Sarah — Avenize's native business operating assistant.
// No external AI provider. All reasoning is generated from live Avenize data.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const H = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const CAP = 100

type Metric = {key?:string; label?:string; current_value?:number|null; target_value?:number|null; change_percent?:number|null}
type Ctx = {businessName:string|null; currency:string; state:string|null; health:number|null; metrics:Metric[]; recommendations:any[]; nba:any; overdue:number|null}
const reply=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...H,'Content-Type':'application/json'}})
const text=(v:any)=>typeof v==='string'?v.replace(/\s+/g,' ').trim():''
const state=(s:string|null)=>({growing:'growing',stable:'stable',scaling:'scaling quickly',stressed:'under pressure',recovering:'recovering',at_risk:'at risk',cash_constrained:'cash-constrained',sales_constrained:'sales-constrained',capacity_constrained:'capacity-constrained',operationally_constrained:'operationally constrained',opportunity_rich:'full of opportunity',insufficient_data:'still being measured'} as Record<string,string>)[s||'']||s||'unknown'
const money=(n:number,c:string)=>`${c==='NGN'?'₦':c}${Math.round(n).toLocaleString()}`
const find=(ctx:Ctx,keys:string[])=>ctx.metrics.find(m=>keys.some(k=>`${m.key||''} ${m.label||''}`.toLowerCase().includes(k)))
const trend=(m?:Metric)=>m?.change_percent==null?'':`, ${m.change_percent>=0?'up':'down'} ${Math.abs(m.change_percent).toFixed(1)}% versus the previous period`

function priorities(ctx:Ctx){
  const p:{score:number;text:string;why:string;source:string}[]=[]
  if(ctx.health!=null&&ctx.health<50)p.push({score:100-ctx.health,text:'Stabilise the weakest part of the business before chasing expansion.',why:`health is ${Math.round(ctx.health)}/100`,source:'business health'})
  if(ctx.overdue!=null&&ctx.overdue>0)p.push({score:100,text:`Follow up on ${ctx.overdue} overdue invoice${ctx.overdue===1?'':'s'} and protect cash collection.`,why:'already-earned cash is waiting to be collected',source:'invoices'})
  const r=find(ctx,['revenue','income','sales'])
  if(r?.current_value!=null&&r.target_value!=null&&r.target_value>0){const pct=r.current_value/r.target_value*100;if(pct<70)p.push({score:90,text:'Close the revenue gap with focused sales activity rather than spreading effort across every opportunity.',why:`revenue is at ${Math.round(pct)}% of target${trend(r)}`,source:`metric:${r.key||'revenue'}`});if(pct>=100)p.push({score:60,text:'Protect the revenue momentum and identify what is driving it so the result can be repeated.',why:`revenue is at ${Math.round(pct)}% of target`,source:`metric:${r.key||'revenue'}`})}
  if(text(ctx.nba?.statement))p.push({score:95,text:text(ctx.nba.statement),why:text(ctx.nba.expectedImpact)||'current next-best-action signal',source:'next best action'})
  for(const r of ctx.recommendations.slice(0,3)){const t=text(r?.statement||r?.title);if(t)p.push({score:75,text:t,why:text(r?.reason||r?.rationale),source:'recommendation engine'})}
  return p.sort((a,b)=>b.score-a.score).slice(0,3)
}

function reason(q:string,ctx:Ctx){
  const s=q.toLowerCase();const r=find(ctx,['revenue','income','sales']);const cash=find(ctx,['cashflow','cash flow','cash','net cash']);const p=priorities(ctx);const top=p[0]
  const has=(...x:string[])=>x.some(k=>s.includes(k))
  if(has('how is my business','how is the business','business doing','business health','overall health','state of my business')){
    const f:string[]=[];if(ctx.state)f.push(`The business is currently ${state(ctx.state)}`);if(ctx.health!=null)f.push(`with a health score of ${Math.round(ctx.health)}/100`);if(r?.current_value!=null)f.push(`revenue is ${money(r.current_value,ctx.currency)} this period${trend(r)}`)
    let a=f.length?f.join(' ')+'.':'I do not have enough live business data to assess health reliably.';if(top)a+=` My read: ${top.text} Why: ${top.why}.`;return {intent:'business_health',confidence:f.length?'high':'low',sources:['business health','business metrics','decision engine'],answer:a}
  }
  if(has('revenue','sales','income','earned','made')){if(r?.current_value==null)return {intent:'revenue',confidence:'low',sources:[],answer:'I do not have a reliable revenue figure in the live business data yet.'};let a=`Revenue this period is ${money(r.current_value,ctx.currency)}${trend(r)}`;if(r.target_value!=null&&r.target_value>0)a+=`. That is ${Math.round(r.current_value/r.target_value*100)}% of the ${money(r.target_value,ctx.currency)} target.`;return {intent:'revenue',confidence:'high',sources:[`metric:${r.key||'revenue'}`],answer:a}}
  if(has('cash','cash flow','cashflow','runway','money in','money out')){if(cash?.current_value==null)return {intent:'cash',confidence:'low',sources:[],answer:'I do not have enough live cash-flow data to give you a reliable cash position.'};return {intent:'cash',confidence:'high',sources:[`metric:${cash.key||'cash'}`],answer:`Net cash this period is ${money(cash.current_value,ctx.currency)}${trend(cash)}. ${ctx.overdue?`There are also ${ctx.overdue} overdue invoice${ctx.overdue===1?'':'s'}, so collections deserve attention.`:'There are no overdue invoices in the current data.'}`}}
  if(has('overdue','unpaid','who owes','receivable','outstanding invoice','invoice')){if(ctx.overdue==null)return {intent:'collections',confidence:'low',sources:[],answer:'Invoice data is not available enough for a reliable collections assessment.'};return {intent:'collections',confidence:'high',sources:['invoices','decision engine'],answer:ctx.overdue===0?'There are no overdue invoices in the current live data.':`There are ${ctx.overdue} overdue invoice${ctx.overdue===1?'':'s'}. I would make collection follow-up a priority because recovering already-earned cash is usually lower-friction than creating new demand.`}}
  if(has('what should i','what do i','priority','what next','next best','focus on','where should i')){if(!top)return {intent:'next_action',confidence:'low',sources:[],answer:'I do not have a strong enough live signal to name a priority yet. I would rather tell you that than invent one.'};return {intent:'next_action',confidence:'high',sources:[top.source],answer:`Your highest-priority move is: ${top.text} Why: ${top.why}.`}}
  if(has('risk','danger','problem','wrong','concern','revenue at risk')){const risks:string[]=[];if(ctx.overdue)risks.push(`${ctx.overdue} overdue invoice${ctx.overdue===1?'':'s'}`);if(r?.current_value!=null&&r.target_value!=null&&r.target_value>0&&r.current_value<r.target_value)risks.push(`revenue at ${Math.round(r.current_value/r.target_value*100)}% of target`);if(ctx.health!=null&&ctx.health<60)risks.push(`health score ${Math.round(ctx.health)}/100`);if(!risks.length)return {intent:'risk',confidence:'medium',sources:['decision engine'],answer:'I do not see a material risk signal in the live data I can access right now. That means the current signals are not strong enough to flag one, not that risk is impossible.'};return {intent:'risk',confidence:'high',sources:['business metrics','invoices','decision engine'],answer:`The strongest current risk signals are: ${risks.join('; ')}. I would address the highest-impact item first.`}}
  const snap:string[]=[];if(ctx.state)snap.push(`state: ${state(ctx.state)}`);if(ctx.health!=null)snap.push(`health: ${Math.round(ctx.health)}/100`);if(r?.current_value!=null)snap.push(`revenue: ${money(r.current_value,ctx.currency)}${trend(r)}`);if(ctx.overdue!=null)snap.push(`overdue invoices: ${ctx.overdue}`);let a=snap.length?`Sarah's current read: ${snap.join('; ')}.`:'I do not have enough live business context to answer that reliably.';if(top)a+=` The strongest action signal is: ${top.text}`;a+=' Tell me the decision you are facing and I will break it into facts, risks and the next move.';return {intent:'business_reasoning',confidence:snap.length?'medium':'low',sources:snap.length?['live business context','decision engine']:[],answer:a}
}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return reply({error:'Method not allowed'},405)
  const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)return reply({error:'Unauthorized'},401)
  const userClient=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${jwt}`}}});const service=createClient(url,serviceKey);const started=Date.now()
  try{
    const {data:ud}=await userClient.auth.getUser();const user=ud?.user;if(!user)return reply({error:'Unauthorized'},401)
    const {data:staff}=await userClient.from('staff').select('id,business_id').eq('user_id',user.id).limit(1).maybeSingle();if(!staff?.business_id)return reply({error:'No business membership.'},403)
    let body:any;try{body=await req.json()}catch{return reply({error:'Invalid JSON'},400)};const q=String(body.question||'').trim();if(!q)return reply({error:'Ask a question.'},400);if(q.length>2000)return reply({error:'Question too long.'},400)
    const {count}=await service.from('copilot_messages').select('id',{count:'exact',head:true}).eq('business_id',staff.business_id).eq('role','user').gte('created_at',new Date(new Date().setHours(0,0,0,0)).toISOString());if((count??0)>=CAP)return reply({error:`Daily limit reached (${CAP} questions per business). Try again tomorrow.`},429)
    const [h,m,r,b,i,bs]=await Promise.allSettled([userClient.rpc('current_business_health',{p_business_id:staff.business_id}),userClient.rpc('current_metrics',{p_business_id:staff.business_id}),userClient.rpc('open_recommendations',{p_business_id:staff.business_id}),userClient.rpc('business_brain',{p_business_id:staff.business_id}),userClient.from('invoices').select('id',{count:'exact',head:true}).lt('due_date',new Date().toISOString()).in('status',['sent','overdue','partial']),userClient.from('businesses').select('name,currency').eq('id',staff.business_id).maybeSingle()])
    const hr=h.status==='fulfilled'?h.value.data:null;const ctx:Ctx={businessName:bs.status==='fulfilled'?bs.value.data?.name??null:null,currency:bs.status==='fulfilled'?bs.value.data?.currency??'NGN':'NGN',state:b.status==='fulfilled'?(b.value.data?.state?.state??b.value.data?.business_state?.state??null):null,health:(Array.isArray(hr)?hr[0]?.overall_score:hr?.overall_score)??null,metrics:m.status==='fulfilled'?(m.value.data||[]):[],recommendations:r.status==='fulfilled'?(r.value.data||[]):[],nba:b.status==='fulfilled'?(b.value.data?.next_best_action??b.value.data?.nba??null):null,overdue:i.status==='fulfilled'?(i.value.count??null):null}
    const result=reason(q,ctx);const snap={businessName:ctx.businessName,state:ctx.state,health:ctx.health,metricKeys:ctx.metrics.map(x=>x.key).slice(0,20)}
    await service.from('copilot_messages').insert([{business_id:staff.business_id,user_id:user.id,role:'user',content:q,context_snapshot:snap},{business_id:staff.business_id,user_id:user.id,role:'assistant',content:result.answer,provider:'native',sources:result.sources,intent:result.intent,context_snapshot:snap}])
    try{await service.rpc('emit_platform_activity',{p_event_type:'ai.completed',p_feature:'ask-avenize',p_business_id:staff.business_id,p_result:'completed',p_severity:'info',p_service:'edge-fn',p_correlation_id:null,p_payload:{intent:result.intent,provider:'native',duration_ms:Date.now()-started}})}catch{}
    return reply({answer:result.answer,sources:result.sources,intent:result.intent,confidence:result.confidence,provider:'native',assistant:'Sarah'})
  }catch(e){console.error('[ask-avenize]',e);return reply({error:'Something went wrong answering that. Try again.'},500)}
})
