import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowUp, Package, Plus, Search, X } from 'lucide-react'
import { useAuth } from '../lib/AuthContext'
import { supabase } from '../lib/supabase'
import { useToast } from '../components/Toast'

type Product={id:string;name:string;sku:string|null;price:number;cost:number|null;stock:number|null;low_stock_threshold:number|null;business_id:string}
type Movement={id:string;product_id:string;change:number;reason:string|null;created_at:string}
const money=(n:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n)

export default function InventoryNigeria(){
 const {staff}=useAuth();const {showToast}=useToast();const bid=staff?.business_id
 const [products,setProducts]=useState<Product[]>([]);const [movements,setMovements]=useState<Movement[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [query,setQuery]=useState('');const [lowOnly,setLowOnly]=useState(false);const [showItem,setShowItem]=useState(false);const [showAdjust,setShowAdjust]=useState(false);const [selected,setSelected]=useState<Product|null>(null);const [saving,setSaving]=useState(false)
 const [form,setForm]=useState({name:'',sku:'',price:'',cost:'',stock:'0',low_stock_threshold:'0'});const [adjust,setAdjust]=useState({change:'',reason:''})
 const load=useCallback(async()=>{if(!bid){setLoading(false);return}setLoading(true);setError(null);const [p,m]=await Promise.all([supabase.from('products').select('id,name,sku,price,cost,stock,low_stock_threshold,business_id').eq('business_id',bid).order('name'),supabase.from('stock_movements').select('id,product_id,change,reason,created_at').eq('business_id',bid).order('created_at',{ascending:false}).limit(200)]);if(p.error||m.error){setError('Inventory data could not be loaded.');setProducts([]);setMovements([])}else{setProducts((p.data??[]) as Product[]);setMovements((m.data??[]) as Movement[])}setLoading(false)},[bid])
 useEffect(()=>{void load()},[load])
 const visible=useMemo(()=>products.filter(p=>(!query||p.name.toLowerCase().includes(query.toLowerCase())||p.sku?.toLowerCase().includes(query.toLowerCase()))&&(!lowOnly||Number(p.stock||0)<=Number(p.low_stock_threshold||0))),[products,query,lowOnly])
 async function createItem(){if(!bid||!form.name.trim()){showToast('Product name is required.','error');return}setSaving(true);const {error:e}=await supabase.from('products').insert({business_id:bid,name:form.name.trim(),sku:form.sku.trim()||null,price:Number(form.price)||0,cost:Number(form.cost)||0,stock:Number(form.stock)||0,low_stock_threshold:Number(form.low_stock_threshold)||0}).select().single();if(e)showToast('Product was not saved.','error');else{showToast('Product created.','success');setShowItem(false);setForm({name:'',sku:'',price:'',cost:'',stock:'0',low_stock_threshold:'0'});void load()}setSaving(false)}
 async function adjustStock(){if(!bid||!staff?.id||!selected||!Number.isInteger(Number(adjust.change))||Number(adjust.change)===0){showToast('Enter a non-zero whole-unit adjustment.','error');return}setSaving(true);const {data,error:e}=await supabase.rpc('adjust_inventory_stock',{p_business_id:bid,p_product_id:selected.id,p_change:Number(adjust.change),p_reason:adjust.reason.trim()||'Manual stock adjustment'});if(e)showToast(e.message||'Stock adjustment failed.','error');else{showToast(`Stock updated to ${data}.`,`success`);setShowAdjust(false);setAdjust({change:'',reason:''});void load()}setSaving(false)}
 const lowCount=products.filter(p=>Number(p.stock||0)<=Number(p.low_stock_threshold||0)).length;const value=products.reduce((s,p)=>s+Number(p.stock||0)*Number(p.cost||0),0)
 return <div className="pb-20"><div className="flex flex-wrap justify-between gap-3 mb-6"><div><h1 className="text-xl font-medium">Inventory</h1><p className="text-sm opacity-70 mt-1">Products and atomic stock movements</p></div><button onClick={()=>setShowItem(true)} className="px-4 py-2 rounded-lg avenize-gradient text-white flex items-center gap-2"><Plus size={16}/>Product</button></div>
 {error&&<div className="p-4 mb-5 rounded-xl border border-[var(--av-danger)]/20 bg-[var(--av-danger-soft)] text-sm">{error}</div>}
 {!error&&<div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-5"><div className="rounded-2xl border p-4"><p className="text-xs opacity-60">Products</p><p className="text-2xl font-semibold">{products.length}</p></div><div className="rounded-2xl border p-4"><p className="text-xs opacity-60">Low stock</p><p className="text-2xl font-semibold">{lowCount}</p></div><div className="rounded-2xl border p-4"><p className="text-xs opacity-60">Stock cost value</p><p className="text-2xl font-semibold">{money(value)}</p><p className="text-[11px] opacity-50">Current quantity × recorded unit cost</p></div></div>}
 <div className="flex flex-wrap gap-2 mb-5"><div className="relative flex-1 min-w-[200px]"><Search size={15} className="absolute left-3 top-3 opacity-50"/><input className="w-full border rounded-lg pl-9 p-2" placeholder="Search products" value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={()=>setLowOnly(v=>!v)} className={`px-3 py-2 rounded-lg border text-sm ${lowOnly?'avenize-gradient text-white':''}`}><AlertTriangle size={14} className="inline mr-1"/>Low stock</button></div>
 <div className="rounded-2xl border divide-y">{loading?<div className="p-8 text-center opacity-60">Loading inventory…</div>:visible.map(p=>{const stock=Number(p.stock||0),threshold=Number(p.low_stock_threshold||0);return <div key={p.id} className="p-4 flex flex-wrap justify-between gap-3"><div><p className="font-medium">{p.name}</p><p className="text-xs opacity-60">{p.sku||'No SKU'} · {money(Number(p.cost||0))} unit cost</p></div><div className="flex items-center gap-4"><div className="text-right"><p className={`font-semibold ${stock<=threshold?'text-[var(--av-danger)]':''}`}>{stock} units</p><p className="text-xs opacity-50">reorder {threshold}</p></div><button onClick={()=>{setSelected(p);setShowAdjust(true)}} className="px-3 py-2 rounded-lg border text-sm">Adjust</button></div></div>)}{!loading&&visible.length===0&&<div className="p-8 text-center opacity-60">No products match this view.</div>}</div>
 <section className="mt-6 rounded-2xl border p-5"><h2 className="font-medium mb-3">Recent stock movements</h2>{movements.slice(0,10).map(m=><div key={m.id} className="py-2 flex justify-between text-sm"><span>{products.find(p=>p.id===m.product_id)?.name||'Product'} · {m.reason||'Stock adjustment'}</span><span className="flex items-center gap-1">{m.change>0?<ArrowUp size={14}/>:<ArrowDown size={14}/>} {m.change>0?'+':''}{m.change}</span></div>)}{movements.length===0&&<p className="text-sm opacity-60">No stock movements recorded.</p>}</section>
 {showItem&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-2xl bg-[var(--av-surface-elevated)] border p-6"><div className="flex justify-between mb-4"><h2 className="font-semibold">New product</h2><button onClick={()=>setShowItem(false)}><X size={18}/></button></div><div className="grid grid-cols-2 gap-3"><input className="border rounded-lg p-2 col-span-2" placeholder="Name" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/><input className="border rounded-lg p-2" placeholder="SKU" value={form.sku} onChange={e=>setForm(v=>({...v,sku:e.target.value}))}/><input className="border rounded-lg p-2" type="number" placeholder="Sell price" value={form.price} onChange={e=>setForm(v=>({...v,price:e.target.value}))}/><input className="border rounded-lg p-2" type="number" placeholder="Unit cost" value={form.cost} onChange={e=>setForm(v=>({...v,cost:e.target.value}))}/><input className="border rounded-lg p-2" type="number" placeholder="Opening stock" value={form.stock} onChange={e=>setForm(v=>({...v,stock:e.target.value}))}/><input className="border rounded-lg p-2" type="number" placeholder="Low stock threshold" value={form.low_stock_threshold} onChange={e=>setForm(v=>({...v,low_stock_threshold:e.target.value}))}/></div><button disabled={saving} onClick={()=>void createItem()} className="w-full mt-4 py-2 rounded-lg avenize-gradient text-white">{saving?'Saving…':'Create product'}</button></div></div>}
 {showAdjust&&selected&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl bg-[var(--av-surface-elevated)] border p-6"><div className="flex justify-between mb-4"><h2 className="font-semibold">Adjust {selected.name}</h2><button onClick={()=>setShowAdjust(false)}><X size={18}/></button></div><p className="text-sm opacity-60 mb-3">Current stock: {selected.stock||0}. The adjustment and movement ledger are committed atomically.</p><input className="w-full border rounded-lg p-2 mb-3" type="number" step="1" placeholder="Change (+/- units)" value={adjust.change} onChange={e=>setAdjust(v=>({...v,change:e.target.value}))}/><input className="w-full border rounded-lg p-2" placeholder="Reason" value={adjust.reason} onChange={e=>setAdjust(v=>({...v,reason:e.target.value}))}/><button disabled={saving} onClick={()=>void adjustStock()} className="w-full mt-4 py-2 rounded-lg avenize-gradient text-white">{saving?'Updating…':'Apply adjustment'}</button></div></div>}
 </div>
}
