import { useCallback, useEffect, useMemo, useState } from 'react'
import { useAuth } from '../lib/AuthContext'
import { useBusiness } from '../lib/BusinessContext'
import { supabase } from '../lib/supabase'
import { useToast } from '../components/Toast'
import { AttendeeSelector, AgendaBuilder } from '../components/MeetingComponents'
import { Calendar, Clock, Plus, Search, Video, Users, Bell, Trash2, ExternalLink, Loader2 } from 'lucide-react'

interface Attendee { id:string; name:string; email:string; status:'pending'|'accepted'|'declined'|'tentative' }
interface Meeting { id:string; title:string; description?:string; date:string; start_time:string; end_time?:string; location?:string; meeting_link?:string; attendees:Attendee[]; agenda?:string; notes?:string; status:'scheduled'|'in_progress'|'completed'|'cancelled'; staff_id:string; business_id:string }
interface AgendaItem { id:string; title:string; duration_minutes:number; completed:boolean }
type Mode='list'|'create'|'detail'|'edit'
const today=()=>new Date().toISOString().slice(0,10)
const time12=(v:string)=>{if(!v)return '';const [hh,mm]=v.split(':');const h=Number(hh);return `${h%12||12}:${mm} ${h>=12?'PM':'AM'}`}
const dateLabel=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString('en-NG',{weekday:'short',day:'numeric',month:'short',year:'numeric'})

export default function Meetings(){
 const {staff}=useAuth(); const {activeBusinessId}=useBusiness(); const {showToast}=useToast(); const businessId=activeBusinessId??staff?.business_id??null
 const [meetings,setMeetings]=useState<Meeting[]>([]); const [loading,setLoading]=useState(true); const [mode,setMode]=useState<Mode>('list'); const [selected,setSelected]=useState<Meeting|null>(null); const [query,setQuery]=useState(''); const [staffList,setStaffList]=useState<any[]>([]); const [invitees,setInvitees]=useState<Attendee[]>([]); const [agenda,setAgenda]=useState<AgendaItem[]>([])
 const [form,setForm]=useState({title:'',description:'',date:today(),start_time:'09:00',end_time:'10:00',location:'',notes:''})
 const load=useCallback(async()=>{if(!businessId){setLoading(false);return}setLoading(true);const {data,error}=await supabase.from('meetings').select('*').eq('business_id',businessId).order('date',{ascending:true}).order('start_time',{ascending:true}).limit(100);if(error){console.error(error);showToast('Failed to load meetings','error')}else setMeetings((data||[]).map((m:any)=>({...m,attendees:Array.isArray(m.attendees)?m.attendees:[]})));setLoading(false)},[businessId,showToast])
 useEffect(()=>{void load()},[load]); useEffect(()=>{if(businessId)supabase.from('staff').select('id,full_name,email').eq('business_id',businessId).then(({data})=>setStaffList(data||[]))},[businessId])
 const reset=()=>{setForm({title:'',description:'',date:today(),start_time:'09:00',end_time:'10:00',location:'',notes:''});setInvitees([]);setAgenda([])}
 const openCreate=()=>{reset();setMode('create')}; const openEdit=(m:Meeting)=>{setSelected(m);setForm({title:m.title,description:m.description||'',date:m.date,start_time:m.start_time,end_time:m.end_time||'',location:m.location||'',notes:m.notes||''});setInvitees(m.attendees||[]);setAgenda(m.agenda?JSON.parse(m.agenda):[]);setMode('edit')}
 const create=async()=>{if(!businessId||!staff?.id||!form.title.trim()){showToast('Meeting title is required','error');return}const {data,error}=await supabase.from('meetings').insert({title:form.title.trim(),description:form.description||null,date:form.date,start_time:form.start_time,end_time:form.end_time||null,location:form.location||null,agenda:agenda.length?JSON.stringify(agenda):null,notes:form.notes||null,attendees:invitees,status:'scheduled',staff_id:staff.id,business_id:businessId}).select().single();if(error){console.error(error);showToast('Failed to schedule meeting','error');return}setMeetings(v=>[...v,data]);reset();setMode('list');showToast('Meeting scheduled','success');for(const a of invitees)await supabase.from('notifications').insert({business_id:businessId,staff_id:a.id,title:'Meeting Invitation',message:`You've been invited to ${data.title} on ${dateLabel(data.date)} at ${time12(data.start_time)}`,type:'meeting',related_id:data.id})}
 const update=async()=>{if(!selected||!form.title.trim())return;const {data,error}=await supabase.from('meetings').update({title:form.title.trim(),description:form.description||null,date:form.date,start_time:form.start_time,end_time:form.end_time||null,location:form.location||null,agenda:agenda.length?JSON.stringify(agenda):null,notes:form.notes||null,attendees:invitees,updated_at:new Date().toISOString()}).eq('id',selected.id).select().single();if(error){showToast('Failed to update meeting','error');return}setMeetings(v=>v.map(m=>m.id===selected.id?data:m));setSelected(data);setMode('detail');showToast('Meeting updated','success')}
 const remove=async(id:string)=>{if(!confirm('Delete this meeting?'))return;const {error}=await supabase.from('meetings').delete().eq('id',id);if(error){showToast('Failed to delete meeting','error');return}setMeetings(v=>v.filter(m=>m.id!==id));setSelected(null);setMode('list');showToast('Meeting deleted','success')}
 const remind=async(m:Meeting)=>{for(const a of m.attendees||[])await supabase.from('notifications').insert({business_id:businessId,staff_id:a.id,title:'Meeting Reminder',message:`${m.title} starts at ${time12(m.start_time)}`,type:'reminder',related_id:m.id});showToast('Reminders sent','success')}
 const filtered=useMemo(()=>meetings.filter(m=>m.title.toLowerCase().includes(query.toLowerCase())),[meetings,query])
 if(mode==='create'||mode==='edit')return <div className="max-w-4xl mx-auto pb-20"><button onClick={()=>setMode('list')} className="mb-6 text-sm text-black/60">← Back to meetings</button><div className="bg-white rounded-2xl border border-black/5 p-6 space-y-6"><div><h1 className="text-2xl font-bold text-black">{mode==='create'?'Schedule meeting':'Edit meeting'}</h1><p className="text-sm text-black/55 mt-1">Meet inside Avenize. No Zoom, Teams or external meeting link is required.</p></div><input className="w-full rounded-xl border border-black/10 p-3" placeholder="Meeting title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="w-full rounded-xl border border-black/10 p-3" placeholder="Description" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="grid md:grid-cols-3 gap-3"><input type="date" className="rounded-xl border border-black/10 p-3" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input type="time" className="rounded-xl border border-black/10 p-3" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/><input type="time" className="rounded-xl border border-black/10 p-3" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></div><input className="w-full rounded-xl border border-black/10 p-3" placeholder="Physical location (optional)" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><AttendeeSelector allStaff={staffList} selectedAttendees={invitees} onAttendeesChange={setInvitees}/><AgendaBuilder items={agenda} onChange={setAgenda}/><textarea className="w-full rounded-xl border border-black/10 p-3" placeholder="Preparation notes" rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button onClick={mode==='create'?create:update} className="w-full rounded-xl bg-[var(--av-primary)] text-white py-3 font-semibold">{mode==='create'?'Schedule Avenize Meeting':'Save changes'}</button></div></div>
 if(mode==='detail'&&selected)return <div className="max-w-5xl mx-auto pb-20"><button onClick={()=>setMode('list')} className="mb-6 text-sm text-black/60">← Back to meetings</button><div className="bg-white rounded-2xl border border-black/5 p-6"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4"><div><span className="text-xs uppercase tracking-wide text-[var(--av-primary)]">Avenize Meeting</span><h1 className="text-3xl font-bold text-black mt-1">{selected.title}</h1><p className="text-black/55 mt-2">{dateLabel(selected.date)} · {time12(selected.start_time)}{selected.end_time?` – ${time12(selected.end_time)}`:''}</p></div><div className="flex gap-2"><a href={selected.meeting_link||`/app/meeting-capture?meeting=${selected.id}`} className="inline-flex items-center gap-2 rounded-xl bg-[var(--av-primary)] text-white px-5 py-3 font-semibold"><Video size={18}/> Join in Avenize</a><button onClick={()=>openEdit(selected)} className="rounded-xl border border-black/10 px-4">Edit</button></div></div>{selected.description&&<p className="mt-6 text-black/70">{selected.description}</p>}<div className="mt-8 grid md:grid-cols-3 gap-4"><div className="rounded-xl bg-[#F8F9FA] p-4"><Calendar size={18}/><p className="font-medium mt-2">{dateLabel(selected.date)}</p></div><div className="rounded-xl bg-[#F8F9FA] p-4"><Clock size={18}/><p className="font-medium mt-2">{time12(selected.start_time)}</p></div><div className="rounded-xl bg-[#F8F9FA] p-4"><Users size={18}/><p className="font-medium mt-2">{selected.attendees?.length||0} participants</p></div></div><div className="mt-8"><h2 className="font-semibold mb-3">Agenda</h2>{selected.agenda?<pre className="whitespace-pre-wrap text-sm text-black/65 bg-[#F8F9FA] rounded-xl p-4">{selected.agenda}</pre>:<p className="text-sm text-black/45">No agenda added.</p>}</div><div className="mt-8 flex gap-2"><button onClick={()=>remind(selected)} className="inline-flex items-center gap-2 rounded-xl border border-black/10 px-4 py-2"><Bell size={16}/> Remind participants</button><button onClick={()=>remove(selected.id)} className="inline-flex items-center gap-2 rounded-xl border border-red-200 text-red-600 px-4 py-2"><Trash2 size={16}/> Delete</button></div></div></div>
 return <div className="pb-20"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-black">Meetings</h1><p className="text-sm text-black/55 mt-1">Host, join and capture meetings directly inside Avenize.</p></div><button onClick={openCreate} className="inline-flex items-center gap-2 rounded-xl bg-[var(--av-primary)] text-white px-5 py-3 font-semibold"><Plus size={18}/> New meeting</button></div><div className="relative mb-6"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-black/35"/><input className="w-full rounded-xl border border-black/10 pl-11 pr-4 py-3" placeholder="Search meetings" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<div className="py-16 flex justify-center"><Loader2 className="animate-spin text-[var(--av-primary)]"/></div>:filtered.length===0?<div className="rounded-2xl border border-dashed border-black/10 py-16 text-center"><Video size={40} className="mx-auto text-black/25 mb-3"/><p className="font-medium">No meetings yet</p><button onClick={openCreate} className="mt-4 text-[var(--av-primary)] font-medium">Schedule your first Avenize meeting</button></div>:<div className="space-y-3">{filtered.map(m=><button key={m.id} onClick={()=>{setSelected(m);setMode('detail')}} className="w-full text-left bg-white rounded-2xl border border-black/5 p-5 hover:border-[var(--av-primary)]/30 transition"><div className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 mb-2"><span className={`text-xs px-2 py-1 rounded-full ${m.status==='completed'?'bg-green-50 text-green-700':m.status==='in_progress'?'bg-blue-50 text-blue-700':'bg-black/[0.04] text-black/60'}`}>{m.status.replace('_',' ')}</span><span className="text-xs text-black/45">{dateLabel(m.date)}</span></div><h3 className="font-semibold text-black">{m.title}</h3><p className="text-sm text-black/55 mt-1">{time12(m.start_time)}{m.end_time?` – ${time12(m.end_time)}`:''} · {m.attendees?.length||0} participants</p></div><ExternalLink size={18} className="text-black/30"/></div></button>)}</div>}</div>
}
