import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Plus, Search, X } from 'lucide-react'
import { useAuth } from '../lib/AuthContext'
import { supabase } from '../lib/supabase'
import { useToast } from '../components/Toast'

type Payment={id:string;type:'income'|'expense';amount:number;method:string;reference:string|null;description:string;category:string|null;invoice_id:string|null;invoice_number:string|null;client_name:string|null;date:string;status:string;provider:string|null;provider_reference:string|null;currency:string|null;reconciled_at:string|null}
const money=(n:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n)
const startOfMonth=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)}

export default function Payments(){
 const {staff}=useAuth();const {showToast}=useToast();const businessId=staff?.business_id
 const [payments,setPayments]=useState<Payment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [from,setFrom]=useState(startOfMonth());const [to,setTo]=useState(new Date().toISOString().slice(0,10));const [query,setQuery]=useState('');const [kind,setKind]=useState<'all'|'income'|'expense'>('all');const [show,setShow]=useState(false);const [saving,setSaving]=useState(false)
 const [form,setForm]=useState({type:'income' as 'income'|'expense',amount:'',method:'bank_transfer',reference:'',description:'',category:'',invoice_id:'',invoice_number:'',client_name:'',date:new Date().toISOString().slice(0,10),notes:''})
 const load=useCallback(async()=>{if(!businessId){setLoading(false);return}setLoading(true);setError(null);const {data,error:e}=await supabase.from('payments').select('id,type,amount,method,reference,description,category,invoice_id,invoice_number,client_name,date,status,provider,provider_reference,currency,reconciled_at').eq('business_id',businessId).gte('date',from).lte('date',to).order('date',{ascending:false}).limit(5000);if(e){setError('Payment data could not be loaded. Totals are unavailable until the ledger can be read.');setPayments([])}else setPayments((data??[]) as Payment[]);setLoading(false)},[businessId,from,to])
 useEffect(()=>{void load()},[load])
 const visible=useMemo(()=>payments.filter(p=>(kind==='all'||p.type===kind)&&(!query||[p.description,p.reference,p.client_name,p.invoice_number].filter(Boolean).some(v=>String(v).toLowerCase().includes(query.toLowerCase())))),[payments,kind,query])
 const income=payments.filter(p=>p.type==='income').reduce((s,p)=>s+Number(p.amount),0),expense=payments.filter(p=>p.type==='expense').reduce((s,p)=>s+Number(p.amount),0)
 async function create(){if(!businessId||!staff?.id||Number(form.amount)<=0||!form.description.trim()){showToast('Enter amount and description.','error');return}setSaving(true);const {data,error:e}=await supabase.from('payments').insert({business_id:businessId,staff_id:staff.id,type:form.type,payment_type:form.type==='income'?'receive':'pay',amount:Number(form.amount),method:form.method,reference:form.reference.trim()||null,description:form.description.trim(),category:form.category.trim()||null,invoice_id:form.invoice_id.trim()||null,invoice_number:form.invoice_number.trim()||null,client_name:form.client_name.trim()||null,date:form.date,notes:form.notes.trim()||null,status:'pending',provider:null,provider_reference:null,allocation_status:'unallocated',currency:'NGN'}).select().single();if(e){showToast('Payment was not saved.','error')}else{setPayments(v=>[data as Payment,...v]);setShow(false);setForm({type:'income',amount:'',method:'bank_transfer',reference:'',description:'',category:'',invoice_id:'',invoice_number:'',client_name:'',date:new Date().toISOString().slice(0,10),notes:''});showToast('Manual payment recorded as pending/unverified.','success')}setSaving(false)}
 return <div className="pb-20"><div className="flex flex-wrap justify-between gap-3 mb-6"><div><h1 className="text-xl font-medium">Payments</h1><p className="text-sm opacity-70 mt-1">Money movement for the selected reporting period</p></div><button onClick={()=>setShow(true)} className="px-4 py-2 rounded-lg avenize-gradient text-white flex items-center gap-2"><Plus size={16}/>Record Payment</button></div>
 <div className="flex flex-wrap gap-2 mb-5"><input type="date" className="border rounded-lg px-3 py-2" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" className="border rounded-lg px-3 py-2" value={to} onChange={e=>setTo(e.target.value)}/><div className="flex border rounded-lg overflow-hidden">{(['all','income','expense'] as const).map(k=><button key={k} onClick={()=>setKind(k)} className={`px-3 py-2 text-sm ${kind===k?'avenize-gradient text-white':''}`}>{k[0].toUpperCase()+k.slice(1)}</button>)}</div><div className="relative flex-1 min-w-[180px]"><Search size={15} className="absolute left-3 top-3 opacity-50"/><input className="w-full border rounded-lg pl-9 pr-3 py-2" placeholder="Search payments" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
 {error&&<div className="p-4 mb-5 rounded-xl border border-[var(--av-danger)]/20 bg-[var(--av-danger-soft)] text-sm">{error}</div>}
 {!error&&<div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-6"><div className="rounded-2xl border p-4"><p className="text-xs opacity-60">Income · {from} to {to}</p><p className="text-2xl font-semibold mt-1">{money(income)}</p></div><div className="rounded-2xl border p-4"><p className="text-xs opacity-60">Expenses · {from} to {to}</p><p className="text-2xl font-semibold mt-1">{money(expense)}</p></div><div className="rounded-2xl border p-4"><p className="text-xs opacity-60">Net · {from} to {to}</p><p className="text-2xl font-semibold mt-1">{money(income-expense)}</p></div></div>}
 <div className="rounded-2xl border divide-y">{loading?<div className="p-8 text-center opacity-60">Loading payment ledger…</div>:visible.map(p=><div key={p.id} className="p-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className={`w-9 h-9 rounded-lg flex items-center justify-center ${p.type==='income'?'bg-[var(--av-success-soft)]':'bg-[var(--av-danger-soft)]'}`}>{p.type==='income'?<ArrowUpRight size={16}/>:<ArrowDownRight size={16}/>}</div><div><p className="font-medium">{p.description}</p><p className="text-xs opacity-60">{p.date} · {p.method} · {p.provider?`Provider: ${p.provider}`:'Manual'}{p.reference?` · ${p.reference}`:''}</p></div></div><div className="text-right"><p className="font-semibold">{p.type==='expense'?'-':''}{money(Number(p.amount))}</p><p className="text-xs opacity-60">{p.status}{p.reconciled_at?' · reconciled':''}</p></div></div>)}{!loading&&visible.length===0&&<div className="p-8 text-center opacity-60">No payments in this period.</div>}</div>
 {show&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-2xl bg-[var(--av-surface-elevated)] border p-6"><div className="flex justify-between mb-4"><h2 className="font-semibold">Record manual payment</h2><button onClick={()=>setShow(false)}><X size={18}/></button></div><p className="text-xs opacity-60 mb-4">Manual entries are recorded as pending/unverified. Gateway-confirmed payments are reconciled separately.</p><div className="grid grid-cols-2 gap-3"><select className="border rounded-lg p-2" value={form.type} onChange={e=>setForm(v=>({...v,type:e.target.value as 'income'|'expense'}))}><option value="income">Income</option><option value="expense">Expense</option></select><input className="border rounded-lg p-2" type="number" min="0" placeholder="Amount" value={form.amount} onChange={e=>setForm(v=>({...v,amount:e.target.value}))}/><input className="border rounded-lg p-2 col-span-2" placeholder="Description" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/><input className="border rounded-lg p-2" type="date" value={form.date} onChange={e=>setForm(v=>({...v,date:e.target.value}))}/><input className="border rounded-lg p-2" placeholder="Reference" value={form.reference} onChange={e=>setForm(v=>({...v,reference:e.target.value}))}/><input className="border rounded-lg p-2 col-span-2" placeholder="Invoice ID (optional)" value={form.invoice_id} onChange={e=>setForm(v=>({...v,invoice_id:e.target.value}))}/></div><button disabled={saving} onClick={()=>void create()} className="w-full mt-4 py-2 rounded-lg avenize-gradient text-white">{saving?'Saving…':'Record as pending'}</button></div></div>}
 </div>
}
