#!/usr/bin/env python3
"""Generate the RPC tenant-guard migration (Session-33 security closure).

For every SECURITY DEFINER function with a business_id param and NO existing
caller guard, emit a CREATE OR REPLACE that adds the canonical membership
guard immediately after BEGIN (plpgsql) or wraps the pure-SELECT sql body in
plpgsql so the guard runs first.

REVOKE-only classes (Brain-poisoning vectors, cron fan-outs, admin helpers)
are revoked from public roles; service role + triggers + pg_cron unaffected.
"""
import re
import glob

CANON_COMMENT = '-- Canonical tenant guard: only members of the business may use this RPC (Session-33 security closure).'

REVOKE_ONLY = sorted({
    # Brain-poisoning vectors (direct event fabrication) — edge fn + triggers only
    'emit_business_event', 'process_business_event', 'handler_propagate_capture',
    'handler_derive_relationships', 'handler_update_entity_freshness',
    'execute_automation_action',
    # Cron fan-outs (run with no user context — must stay service-role only)
    'detect_customer_inactive_all', 'detect_contracts_expiring_all', 'detect_payroll_due_all',
    'reprocess_failed_automations', 'run_due_automations', 'evaluate_platform_alerts',
    'scan_all_business_data_quality', 'compute_all_business_health', 'run_all_recommendation_rules',
    'refresh_all_business_metrics',
    'detect_customer_inactive', 'detect_contracts_expiring', 'detect_payroll_due',
    # Admin-only
    'grant_business_plan', 'seed_ai_roles', '_ensure_test_auth_user',
})

BIZ_PARAM_RE = re.compile(r'\b(p_\w*business_id)\b', re.IGNORECASE)
FUNC_RE = re.compile(
    r'CREATE\s+OR\s+REPLACE\s+FUNCTION\s+(?:public\.)?([a-zA-Z_][\w]*)\s*\((.*?)\)',
    re.IGNORECASE | re.DOTALL,
)

def guard_line(param):
    return (CANON_COMMENT + '\n'
            '  IF NOT EXISTS (SELECT 1 FROM public.get_current_staff() cs WHERE cs.business_id = '
            + param + ') THEN\n    RETURN;\n  END IF;')

def split_functions(sql):
    results = []
    sig_re = re.compile(r'CREATE\s+OR\s+REPLACE\s+FUNCTION\s+(?:public\.)?([a-zA-Z_][\w]*)\s*\(', re.IGNORECASE)
    for m in sig_re.finditer(sql):
        name = m.group(1)
        depth = 1
        i = m.end()
        while depth > 0 and i < len(sql):
            if sql[i] == '(':
                depth += 1
            elif sql[i] == ')':
                depth -= 1
            i += 1
        params = sql[m.end(): i - 1]
        rest = sql[i:]
        as_m = re.search(r'\bAS\s+(\$[\w$]*\$)', rest, re.IGNORECASE)
        if not as_m:
            continue
        tag = as_m.group(1)
        sig_tail = sql[i: i + as_m.start()].strip()
        body_start = sql.find(tag, i) + len(tag)
        body_end = sql.find(tag, body_start)
        if body_end == -1:
            continue
        body = sql[body_start:body_end]
        tail = sql[body_end + len(tag): body_end + len(tag) + 600].split(';')[0].strip()
        results.append({'name': name, 'params': params.strip(), 'sig_tail': sig_tail,
                        'body': body, 'tail': tail})
    return results

def main():
    latest = {}
    for path in sorted(p for p in glob.glob('supabase/migrations/*.sql') if 'rpc_tenant_guards' not in p):
        sql = open(path, encoding='utf-8', errors='replace').read()
        for f in split_functions(sql):
            f['secdef'] = bool(re.search(r'SECURITY\s+DEFINER', f['tail'], re.IGNORECASE))
            f['lang'] = 'plpgsql' if re.search(r'LANGUAGE\s+plpgsql', f['tail'], re.IGNORECASE) else (
                'sql' if re.search(r'LANGUAGE\s+sql', f['tail'], re.IGNORECASE) else 'other')
            f['migration'] = path.split('/')[-1]
            latest[(f['name'], f['params'])] = f

    out = ['-- Session-33 security closure: RPC tenant guards (GENERATED by scripts/gen_rpc_tenant_guards.py)',
           '-- SECURITY DEFINER functions with a business_id param are explicitly gated to members',
           '-- (empty result for non-members). REVOKE-only classes (Brain-poisoning vectors, cron',
           '-- fan-outs, admin helpers) are revoked from public roles — service role unaffected.', '']

    transformed = 0
    for (name, params), f in sorted(latest.items(), key=lambda kv: kv[0][0]):
        if not f['secdef'] or name in REVOKE_ONLY:
            continue
        body = f['body']
        if re.search(r'get_current_staff|auth\.uid\(\)|is_platform_admin', body):
            continue  # already guarded
        pm = BIZ_PARAM_RE.search(params)
        if not pm:
            continue
        bparam = pm.group(1)

        if f['lang'] == 'plpgsql':
            bm = re.search(r'\bBEGIN\b', body, re.IGNORECASE)
            if not bm:
                continue
            sig = f['sig_tail']
            is_void = bool(re.match(r'RETURNS\s+VOID\b', sig, re.IGNORECASE))
            setof = bool(re.search(r'RETURNS\s+(SETOF\b|TABLE\b)', sig, re.IGNORECASE))
            ret_stmt = 'RETURN NULL;' if (not setof and not is_void) else 'RETURN;'
            guard = guard_line(bparam).replace('RETURN;', ret_stmt)
            new_body = body[:bm.end()] + '\n' + guard + '\n' + body[bm.end():]
            new_tail = f['tail']
        elif f['lang'] == 'sql':
            setof = bool(re.search(r'RETURNS\s+(SETOF\b|TABLE\b)', f['sig_tail'], re.IGNORECASE))
            sql_body = body.strip().rstrip(';')
            guard_ret = 'RETURN;' if setof else 'RETURN NULL;'
            ret_stmt = ('RETURN QUERY ' + sql_body + ';') if setof else ('RETURN (' + sql_body + ');')
            new_body = '\nBEGIN\n' + guard_line(bparam).replace('RETURN;', guard_ret) + '\n  ' + ret_stmt + '\nEND;\n'
            new_tail = re.sub(r'LANGUAGE\s+sql', 'LANGUAGE plpgsql', f['tail'], flags=re.IGNORECASE)
        else:
            continue

        out.append(f'CREATE OR REPLACE FUNCTION public.{name}({params})')
        out.append(f['sig_tail'])
        out.append('AS $guard$')
        out.append(new_body)
        out.append(f'$guard$ {new_tail};')
        out.append('')
        transformed += 1

    out.append('-- REVOKE-only classes (Brain-poisoning vectors + cron fan-outs + admin helpers).')
    out.append('-- Each guarded by a DO-block so re-application is idempotent even when a name')
    out.append('-- was never created on a given DB.')
    for fn in REVOKE_ONLY:
        for stmt in (f"REVOKE EXECUTE ON FUNCTION public.{fn} FROM PUBLIC",
                     f"REVOKE EXECUTE ON FUNCTION public.{fn} FROM authenticated",
                     f"REVOKE EXECUTE ON FUNCTION public.{fn} FROM anon",
                     f"GRANT EXECUTE ON FUNCTION public.{fn} TO service_role"):
            out.append(f"DO $$ BEGIN EXECUTE '{stmt}'; EXCEPTION WHEN undefined_function THEN NULL; END $$;")

    print(f'transformed={transformed}')
    return '\n'.join(out) + '\n'

if __name__ == '__main__':
    migration = main()
    open('/tmp/rpc_guards.sql', 'w').write(migration)
    print(f'migration lines: {len(migration.splitlines())}')
