#!/usr/bin/env python3
"""Verify production against the Avenize Production Contract.

Reads supabase/contract/production_contract.json (generated by
scripts/generate_contract_manifest.py) and checks the LIVE project:

  tables/views  -> PostgREST OpenAPI (GET /rest/v1/)
  functions     -> PostgREST OpenAPI /rpc/* paths + parameter drift
  buckets       -> Storage API (GET /storage/v1/bucket) [service key required]
  edge functions-> OPTIONS /functions/v1/<name> (deployed = not 404)

Classification per the Production Constitution:
  OK                        - object exists, signature matches
  CONTRACT_DRIFT            - exists with wrong signature  -> repair via the
                              canonical migration (report names the file)
  MISSING / AUTO_REPAIR_SAFE- apply the canonical migration (report names it)
  MISSING / SECURITY_REPAIR_REQUIRED
                            - security-sensitive; never repaired silently;
                              operator applies the canonical migration after
                              review and an incident is recorded

Usage:
  SUPABASE_URL=https://<ref>.supabase.co \
  SUPABASE_KEY=<publishable-or-service-key> \
  python3 scripts/verify_production_contract.py [--json out.json] [--frontend-only]

Exit code: 0 when the contract holds, 1 otherwise.
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = ROOT / "supabase" / "contract" / "production_contract.json"

# Objects that must exist before the app can function at all; a failure in any
# of these is a hard FAIL even in --frontend-only mode.
def http_get(url, key, timeout=30):
    req = urllib.request.Request(
        url,
        headers={"apikey": key, "Authorization": f"Bearer {key}", "Accept": "application/json"},
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=timeout) as res:
        return res.status, res.read().decode("utf-8", errors="replace")


def probe_edge_function(base_url, name, key, timeout=15):
    req = urllib.request.Request(
        f"{base_url}/functions/v1/{name}",
        headers={"apikey": key, "Authorization": f"Bearer {key}"},
        method="OPTIONS",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as res:
            return res.status
    except urllib.error.HTTPError as e:
        return e.code
    except OSError:
        return 0


TYPE_ALIASES = [
    ("character varying", "text"),
    ("timestamp with time zone", "timestamptz"),
    ("timestamp without time zone", "timestamp"),
    ("double precision", "float8"),
    ("bigserial", "int8"),
    ("bigint", "int8"),
    ("smallint", "int2"),
    ("integer", "int4"),
    ("int", "int4"),
    ("serial", "int4"),
    ("decimal", "numeric"),
    ("bool", "boolean"),
]


def normalize_args(args: str) -> str:
    import re

    s = re.sub(r"\s+", " ", (args or "").lower()).strip()
    for old, new in TYPE_ALIASES:
        s = re.sub(rf"\b{re.escape(old)}\b", new, s)
    return s


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", dest="json_out", default=str(ROOT / "supabase" / "contract" / "verification_report.json"))
    parser.add_argument("--frontend-only", action="store_true",
                        help="only check objects the frontend actually references (the user-facing contract)")
    args = parser.parse_args()

    base_url = os.environ.get("SUPABASE_URL", "").rstrip("/")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_KEY") or os.environ.get("SUPABASE_ANON_KEY") or ""
    if not base_url or not key:
        print("ERROR: set SUPABASE_URL and SUPABASE_KEY (or SUPABASE_SERVICE_ROLE_KEY)", file=sys.stderr)
        sys.exit(2)

    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))

    # --- PostgREST probing. Preferred: root OpenAPI spec (elevated key).
    # The root returns 401 to publishable keys by design, so publishable-key
    # runs fall back to per-object HEAD/POST probes. RPC existence is decided
    # from the PGRST error body ("no matches...schema cache" / PGRST202 =
    # missing; anything else = present). Signature drift needs the spec;
    # probe-mode RPCs without spec are reported as existence-only.

    def table_exists(name):
        req = urllib.request.Request(
            f"{base_url}/rest/v1/{name}?limit=0",
            headers={"apikey": key, "Authorization": f"Bearer {key}"},
            method="HEAD",
        )
        try:
            with urllib.request.urlopen(req, timeout=15):
                return True
        except urllib.error.HTTPError as e:
            return e.code != 404
        except Exception:
            return None

    def rpc_probe(name):
        body_txt = ""
        req = urllib.request.Request(
            f"{base_url}/rest/v1/rpc/{name}",
            data=b"{}",
            headers={
                "apikey": key, "Authorization": f"Bearer {key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=15) as res:
                body_txt = res.read().decode("utf-8", errors="replace")
                code = res.status
        except urllib.error.HTTPError as e:
            body_txt = e.read().decode("utf-8", errors="replace")
            code = e.code
        except Exception:
            return None
        # PostgREST phrases this differently across versions ("no matches
        # found" vs "no matches were found") — match on the stable fragments
        # or the PGRST202 code, never the full sentence.
        if ("no matches" in body_txt and "schema cache" in body_txt) or '"PGRST202"' in body_txt:
            return False
        return code is not None and not (code == 404 and "not found" in body_txt.lower())

    spec_mode = False
    live_tables = set()
    live_rpcs = {}
    try:
        status, body = http_get(f"{base_url}/rest/v1/", key)
        if status == 200:
            spec = json.loads(body)
            if isinstance(spec, dict) and "paths" in spec:
                spec_mode = True
                paths = spec["paths"]
                live_tables = {p.lstrip("/") for p in paths if not p.startswith("/rpc/")}
                for p, info in paths.items():
                    if not p.startswith("/rpc/"):
                        continue
                    name = p[len("/rpc/"):]
                    params = []
                    post = info.get("post") or {}
                    for prm in post.get("parameters", []):
                        if prm.get("in") == "query" and prm.get("name") != "select":
                            params.append(prm["name"])
                    live_rpcs.setdefault(name, set()).add(tuple(sorted(params)))
    except Exception:
        spec_mode = False
    if not spec_mode:
        print("note: OpenAPI spec not readable with this key — probing per object")

    # --- Storage buckets (needs a service key; publishable key gets 403) ---
    live_buckets = None
    try:
        bstatus, bbody = http_get(f"{base_url}/storage/v1/bucket", key)
        if bstatus == 200:
            live_buckets = {b.get("name") or b.get("id") for b in json.loads(bbody)}
    except Exception:
        live_buckets = None

    results = {"ok": [], "missing": [], "drift": [], "unknown": []}
    objects = contract["objects"]
    if args.frontend_only:
        objects = [o for o in objects if o.get("frontend_referenced")]

    for obj in objects:
        kind, name = obj["kind"], obj["name"]
        entry = {
            "kind": kind, "name": name,
            "defined_in": obj["defined_in"],
            "security_sensitive": obj["security_sensitive"],
            "classification": None,
        }
        if kind in ("table", "view"):
            exists = (name in live_tables) if spec_mode else table_exists(name)
            if exists is True:
                results["ok"].append(entry)
            elif exists is None:
                entry["classification"] = "UNREACHABLE"
                results["unknown"].append(entry)
            else:
                entry["classification"] = (
                    "SECURITY_REPAIR_REQUIRED" if obj["security_sensitive"] else "AUTO_REPAIR_SAFE"
                )
                results["missing"].append(entry)
        elif kind == "function":
            if not spec_mode:
                exists = rpc_probe(name)
                if exists is True:
                    results["ok"].append(entry)
                elif exists is None:
                    entry["classification"] = "UNREACHABLE"
                    results["unknown"].append(entry)
                else:
                    entry["classification"] = (
                        "SECURITY_REPAIR_REQUIRED" if obj["security_sensitive"] else "AUTO_REPAIR_SAFE"
                    )
                    results["missing"].append(entry)
            elif name not in live_rpcs:
                entry["classification"] = (
                    "SECURITY_REPAIR_REQUIRED" if obj["security_sensitive"] else "AUTO_REPAIR_SAFE"
                )
                results["missing"].append(entry)
            else:
                expected = {tuple(sorted(p.split(" ")[0] for p in (sig.split(", ") if sig else []) if p))
                            for sig in obj.get("signatures", [])}
                expected = {e for e in expected if e != ()}
                actual = live_rpcs.get(name, set())
                if not expected or expected & actual:
                    results["ok"].append(entry)
                else:
                    entry["classification"] = (
                        "SECURITY_REPAIR_REQUIRED" if obj["security_sensitive"] else "CONTRACT_DRIFT"
                    )
                    entry["expected_params"] = sorted(expected)
                    entry["actual_params"] = sorted(actual)
                    results["drift"].append(entry)
        elif kind == "bucket":
            if live_buckets is None:
                entry["classification"] = "UNKNOWN_NO_SERVICE_KEY"
                results["unknown"].append(entry)
            elif name in live_buckets:
                results["ok"].append(entry)
            else:
                entry["classification"] = "AUTO_REPAIR_SAFE"
                results["missing"].append(entry)

    # --- Edge functions ---
    edge_results = []
    for fn in contract.get("edge_functions", []):
        code = probe_edge_function(base_url, fn, key)
        edge_results.append({"name": fn, "deployed": code != 404, "http": code})

    failed = len(results["missing"]) + len(results["drift"])
    report = {
        "target": base_url,
        "frontend_only": args.frontend_only,
        "summary": {
            "ok": len(results["ok"]),
            "missing": len(results["missing"]),
            "drift": len(results["drift"]),
            "unknown": len(results["unknown"]),
            "edge_functions_missing": [e["name"] for e in edge_results if not e["deployed"]],
        },
        "missing": results["missing"],
        "drift": results["drift"],
        "unknown": results["unknown"],
        "edge_functions": edge_results,
    }
    Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json_out).write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print("Avenize Production Contract")
    print("─" * 28)
    print(f"Objects checked : {len(objects)}")
    print(f"OK              : {len(results['ok'])}")
    print(f"Missing         : {len(results['missing'])}")
    print(f"Drift           : {len(results['drift'])}")
    print(f"Unknown         : {len(results['unknown'])}")
    for e in edge_results:
        print(f"  edge {e['name']:<28} {'DEPLOYED' if e['deployed'] else 'MISSING'} (http {e['http']})")
    if results["missing"]:
        print("\nMissing objects (apply the named canonical migration):")
        for m in results["missing"][:40]:
            print(f"  [{m['classification']}] {m['kind']} {m['name']}  <- {m['defined_in']}")
    if results["drift"]:
        print("\nSignature drift (repair via the named canonical migration):")
        for d in results["drift"][:20]:
            print(f"  [{d['classification']}] function {d['name']}  <- {d['defined_in']}")
    print(f"\nRESULT: {'CONTRACT HOLDS' if failed == 0 and all(e['deployed'] for e in edge_results) else 'CONTRACT BROKEN'}")
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
